# -*- coding: utf-8 -*-
"""cropapp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uo4oc3--KEDNBww_xMUxfD1CT36OIn03
"""

import streamlit as st
import numpy as np
import joblib
from tensorflow.keras.models import load_model

def load_all():
    model = load_model("crop_model.keras")
    scaler = joblib.load("scaler.pkl")
    label_encoder = joblib.load("label_encoder.pkl")
    return model, scaler, label_encoder

model, scaler, label_encoder = load_all()

st.title("🌾 AI Crop Recommendation (RNN + Streamlit)")
st.write("Enter soil and climate parameters to get a crop recommendation.")

Temperature = st.number_input("Temperature", value=30.0)
Humidity = st.number_input("Humidity", value=60.0)
Rainfall = st.number_input("Rainfall", value=120.0)
Soil_Moisture = st.number_input("Soil Moisture", value=50.0)
Soil_pH = st.number_input("Soil pH", value=6.5)

if st.button("Predict"):

    # Create input array
    features = np.array([[Temperature, Humidity, Rainfall, Soil_Moisture, Soil_pH]])

    # Scale features
    features_scaled = scaler.transform(features)   # SHAPE = (1,5)

    # Predict
    pred = model.predict(features_scaled)
    idx = np.argmax(pred)
    crop = label_encoder.inverse_transform([idx])[0]

    st.success(f"Recommended Crop: {crop}")